language: python
python:
  - "2.7"
before_install:
  - apt-get install redis-server
  - pip install codecov
  - service redis-server restart
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
script:
  - coverage run --source=husky setup.py test
after_success:
  - codecov