language: python
python:
  - "2.7"
before_install:
  - pip install codecov
services: redis
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
script:
  - coverage run --source=husky setup.py test
after_success:
  - codecov