from __future__ import absolute_import
from husky.tasks.celery import app
from husky.tasks.stock_quote_tasks import crawl_nasdaq_stock_quote_batch
from husky.tasks.stock_history_tasks import update_all_stock_history